version: "3.7"
services:
  mariadb:
    image: mariadb:latest
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=myDb
    - MYSQL_USER=user
    - MYSQL_PASSWORD=mdp
    ports:
      - "3307:3306"
  www:
    build:
      context: ./php-apache/
      dockerfile: Dockerfile
    volumes:
      - ./../:/var/www/html/
    ports:
      - "82:80"
    depends_on:
      - mariadb